apiVersion: v1
kind: Service
metadata:
  name: gov
  namespace: gitops
spec:
  type: ClusterIP
  selector:
    app: gov
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
